<?php

namespace Logixs\Modules\Site\Enrollment\Models;

use InvalidArgumentException;

class CountryTelephoneCode
{
    /**@var int * */
    private $id;
    /**@var string * */
    private $code;

    private function __construct(int $id, string $code)
    {
        $this->id = $id;
        $this->code = $code;
    }

    public function id(): int
    {
        return $this->id;
    }

    public function code(): string
    {
        return $this->code;
    }

    public static function formId(int $id): self
    {
        $items = self::all();
        foreach ($items as $item) {
            if ($item->id() == $id) {
                return $item;
            }
        }
        throw new InvalidArgumentException(sprintf('invalid telephone code value: %d', $id));
    }

    public static function all(): array
    {
        return [
            new self(1, '(' . 'Abkhazia' . ')' . '+7 840'),
            new self(2, '(' . 'Afghanistan' . ')' . '+93'),
            new self(3, '(' . 'Albania' . ')' . '+355'),
            new self(4, '(' . 'Algeria' . ')' . '+213'),
            new self(5, '(' . 'American Samoa' . ')' . '+1 684'),
            new self(6, '(' . 'Andorra' . ')' . '+376'),
            new self(7, '(' . 'Angola' . ')' . '+244'),
            new self(8, '(' . 'Anguilla' . ')' . '+1 264'),
            new self(9, '(' . 'Antigua and Barbuda' . ')' . '+1 268'),
            new self(10, '(' . 'Argentina' . ')' . '+54'),
            new self(11, '(' . 'Armenia' . ')' . '+374'),
            new self(12, '(' . '297' . ')' . '+Aruba'),
            new self(13, '(' . 'Ascension' . ')' . '+247'),
            new self(14, '(' . 'Australia' . ')' . '+61'),
            new self(15, '(' . 'Australian External Territories' . ')' . '+672'),
            new self(16, '(' . 'Austria' . ')' . '+43'),
            new self(17, '(' . 'Azerbaijan' . ')' . '+994'),
            new self(18, '(' . 'Bahamas' . ')' . '+1 242'),
            new self(19, '(' . 'Bahrain' . ')' . '+973'),
            new self(20, '(' . 'Bangladesh' . ')' . '+880'),
            new self(21, '(' . 'Barbados' . ')' . '+1 246'),
            new self(22, '(' . 'Barbuda' . ')' . '+1 268'),
            new self(23, '(' . 'Belarus' . ')' . '+375'),
            new self(24, '(' . 'Belgium' . ')' . '+32'),
            new self(25, '(' . 'Belize' . ')' . '+501'),
            new self(26, '(' . 'Benin' . ')' . '+229'),
            new self(27, '(' . 'Bermuda' . ')' . '+1 441'),
            new self(28, '(' . 'Bhutan' . ')' . '+975'),
            new self(29, '(' . 'Bolivia' . ')' . '+591'),
            new self(30, '(' . 'Bosnia and Herzegovina' . ')' . '+387'),
            new self(31, '(' . 'Botswana' . ')' . '+267'),
            new self(32, '(' . 'Brazil' . ')' . '+55'),
            new self(33, '(' . 'British Indian Ocean Territory' . ')' . '+246'),
            new self(34, '(' . 'British Virgin Islands' . ')' . '+1 284'),
            new self(35, '(' . 'Brunei' . ')' . '+673'),
            new self(36, '(' . 'Bulgaria' . ')' . '+359'),
            new self(37, '(' . 'Burkina Faso' . ')' . '+226'),
            new self(38, '(' . 'Burundi' . ')' . '+257'),
            new self(39, '(' . 'Cambodia' . ')' . '+855'),
            new self(40, '(' . 'Cameroon' . ')' . '+237'),
            new self(41, '(' . 'Canada' . ')' . '+1'),
            new self(42, '(' . 'Cape Verde' . ')' . '+238'),
            new self(43, '(' . 'Cayman Islands' . ')' . '+345'),
            new self(44, '(' . 'Central African Republic' . ')' . '+236'),
            new self(45, '(' . 'Chad' . ')' . '+235'),
            new self(46, '(' . 'Chile' . ')' . '+56'),
            new self(47, '(' . 'China' . ')' . '+86'),
            new self(48, '(' . 'Christmas Island' . ')' . '+61'),
            new self(49, '(' . 'Cocos-Keeling Islands' . ')' . '+61'),
            new self(51, '(' . 'Colombia' . ')' . '+57'),
            new self(52, '(' . 'Comoros' . ')' . '+269'),
            new self(53, '(' . 'Congo' . ')' . '+242'),
            new self(54, '(' . 'Congo, Dem. Rep. of (Zaire)' . ')' . '+243'),
            new self(55, '(' . 'Cook Islands' . ')' . '+682'),
            new self(56, '(' . 'Costa Rica' . ')' . '+506'),
            new self(57, '(' . 'Croatia' . ')' . '+385'),
            new self(58, '(' . 'Cuba' . ')' . '+53'),
            new self(59, '(' . 'Curacao' . ')' . '+599'),
            new self(60, '(' . 'Cyprus' . ')' . '+537'),
            new self(61, '(' . 'Czech Republic' . ')' . '+420'),
            new self(62, '(' . 'Denmark' . ')' . '+45'),
            new self(63, '(' . 'Diego Garcia' . ')' . '+246'),
            new self(64, '(' . 'Djibouti' . ')' . '+253'),
            new self(65, '(' . 'Dominica' . ')' . '+1 767'),
            new self(66, '(' . 'Dominican Republic' . ')' . '+1 809'),
            new self(67, '(' . 'East Timor' . ')' . '+670'),
            new self(68, '(' . 'Easter Island' . ')' . '+56'),
            new self(69, '(' . 'Ecuador' . ')' . '+593'),
            new self(70, '(' . 'Egypt' . ')' . '+20'),
            new self(71, '(' . 'El Salvador' . ')' . '+503'),
            new self(72, '(' . 'Equatorial Guinea' . ')' . '+240'),
            new self(73, '(' . 'Eritrea' . ')' . '+291'),
            new self(74, '(' . 'Estonia' . ')' . '+372'),
            new self(75, '(' . 'Ethiopia' . ')' . '+251'),
            new self(76, '(' . 'Falkland Islands' . ')' . '+500'),
            new self(77, '(' . 'Faroe Islands' . ')' . '+298'),
            new self(78, '(' . 'Fiji' . ')' . '+679'),
            new self(79, '(' . 'Finland' . ')' . '+358'),
            new self(80, '(' . 'France' . ')' . '+33'),
            new self(81, '(' . 'French Antilles' . ')' . '+596'),
            new self(82, '(' . 'French Guiana' . ')' . '+594'),
            new self(83, '(' . 'French Polynesia' . ')' . '+689'),
            new self(84, '(' . 'Gabon' . ')' . '+241'),
            new self(85, '(' . 'Gambia' . ')' . '+220'),
            new self(86, '(' . 'Georgia' . ')' . '+995'),
            new self(87, '(' . 'Germany' . ')' . '+49'),
            new self(88, '(' . 'Ghana' . ')' . '+233'),
            new self(89, '(' . 'Gibraltar' . ')' . '+350'),
            new self(90, '(' . 'Greece' . ')' . '+30'),
            new self(91, '(' . 'Greenland' . ')' . '+299'),
            new self(92, '(' . 'Grenada' . ')' . '+1 473'),
            new self(93, '(' . 'Guadeloupe' . ')' . '+590'),
            new self(94, '(' . 'Guam' . ')' . '+1 671'),
            new self(95, '(' . 'Guatemala' . ')' . '+502'),
            new self(96, '(' . 'Guinea' . ')' . '+224'),
            new self(97, '(' . 'Guinea-Bissau' . ')' . '+245'),
            new self(98, '(' . 'Guyana' . ')' . '+595'),
            new self(99, '(' . 'Haiti' . ')' . '+509'),
            new self(100, '(' . 'Honduras' . ')' . '+504'),
            new self(101, '(' . 'Hong Kong SAR China' . ')' . '+852'),
            new self(102, '(' . 'Hungary' . ')' . '+36'),
            new self(103, '(' . 'Iceland' . ')' . '+354'),
            new self(104, '(' . 'India' . ')' . '+91'),
            new self(105, '(' . 'Indonesia' . ')' . '+62'),
            new self(106, '(' . 'Iran' . ')' . '+98'),
            new self(107, '(' . 'Iraq' . ')' . '+964'),
            new self(108, '(' . 'Ireland' . ')' . '+353'),
            new self(109, '(' . 'Israel' . ')' . '+972'),
            new self(110, '(' . 'Italy' . ')' . '+39'),
            new self(111, '(' . 'Ivory Coast' . ')' . '+225'),
            new self(11, '(' . 'Jamaica' . ')' . '++1 876'),
            new self(113, '(' . 'Japan' . ')' . '+81'),
            new self(114, '(' . 'Jordan' . ')' . '+962'),
            new self(115, '(' . 'Kazakhstan' . ')' . '++7 7'),
            new self(116, '(' . 'Kenya' . ')' . '+254'),
            new self(117, '(' . 'Kiribati' . ')' . '+686'),
            new self(118, '(' . 'Kuwait' . ')' . '+965'),
            new self(119, '(' . 'Kyrgyzstan' . ')' . '+996'),
            new self(120, '(' . 'Laos' . ')' . '+856'),
            new self(121, '(' . 'Latvia' . ')' . '+371'),
            new self(122, '(' . 'Lebanon' . ')' . '+961'),
            new self(123, '(' . 'Lesotho' . ')' . '+266'),
            new self(124, '(' . 'Liberia' . ')' . '+231'),
            new self(125, '(' . 'Libya' . ')' . '+218'),
            new self(126, '(' . 'Liechtenstein' . ')' . '+423'),
            new self(127, '(' . 'Lithuania' . ')' . '+370'),
            new self(128, '(' . 'Luxembourg' . ')' . '+352'),
            new self(129, '(' . 'Macau SAR China' . ')' . '+853'),
            new self(130, '(' . 'Macedonia' . ')' . '+389'),
            new self(131, '(' . 'Madagascar' . ')' . '+261'),
            new self(132, '(' . 'Malawi' . ')' . '+265'),
            new self(133, '(' . 'Malaysia' . ')' . '+60'),
            new self(134, '(' . 'Maldives' . ')' . '+960'),
            new self(135, '(' . 'Mali' . ')' . '+223'),
            new self(136, '(' . 'Malta' . ')' . '+356'),
            new self(137, '(' . 'Marshall Islands' . ')' . '+692'),
            new self(138, '(' . 'Martinique' . ')' . '+596'),
            new self(139, '(' . 'Mauritania' . ')' . '+222'),
            new self(140, '(' . 'Mauritius' . ')' . '+230'),
            new self(141, '(' . 'Mayotte' . ')' . '+262'),
            new self(142, '(' . 'Mexico' . ')' . '+52'),
            new self(143, '(' . 'Micronesia' . ')' . '+691'),
            new self(144, '(' . 'Midway Island' . ')' . '+1 808'),
            new self(145, '(' . 'Moldova' . ')' . '+373'),
            new self(146, '(' . 'Monaco' . ')' . '+377'),
            new self(147, '(' . 'Mongolia' . ')' . '+976'),
            new self(148, '(' . 'Montenegro' . ')' . '+382'),
            new self(149, '(' . 'Montserrat' . ')' . '+1664'),
            new self(150, '(' . 'Morocco' . ')' . '+212'),
            new self(151, '(' . 'Myanmar' . ')' . '+95'),
            new self(152, '(' . 'Namibia' . ')' . '+264'),
            new self(153, '(' . 'Nauru' . ')' . '+674'),
            new self(154, '(' . 'Nepal' . ')' . '+977'),
            new self(155, '(' . 'Netherlands' . ')' . '+31'),
            new self(156, '(' . 'Netherlands Antilles' . ')' . '+599'),
            new self(157, '(' . 'Nevis' . ')' . '+1 869'),
            new self(158, '(' . 'New Caledonia' . ')' . '+687'),
            new self(159, '(' . 'New Zealand' . ')' . '+64'),
            new self(160, '(' . 'Nicaragua' . ')' . '+505'),
            new self(161, '(' . 'Niger' . ')' . '+227'),
            new self(162, '(' . 'Nigeria' . ')' . '+234'),
            new self(163, '(' . 'Niue' . ')' . '+683'),
            new self(164, '(' . 'Norfolk Island' . ')' . '+672'),
            new self(165, '(' . 'North Korea' . ')' . '+850'),
            new self(166, '(' . 'Northern Mariana Islands' . ')' . '+1 670'),
            new self(167, '(' . 'Norway' . ')' . '+47'),
            new self(168, '(' . 'Oman' . ')' . '+968'),
            new self(169, '(' . 'Pakistan' . ')' . '+92'),
            new self(170, '(' . 'Palau' . ')' . '+680'),
            new self(171, '(' . 'Palestinian Territory' . ')' . '+970'),
            new self(172, '(' . 'Panama' . ')' . '+507'),
            new self(173, '(' . 'Papua New Guinea' . ')' . '+675'),
            new self(174, '(' . 'Paraguay' . ')' . '+595'),
            new self(175, '(' . 'Peru' . ')' . '+51'),
            new self(176, '(' . 'Philippines' . ')' . '+63'),
            new self(177, '(' . 'Poland' . ')' . '+48'),
            new self(178, '(' . 'Portugal' . ')' . '+351'),
            new self(179, '(' . 'Puerto Rico' . ')' . '+1 787'),
            new self(180, '(' . 'Qatar' . ')' . '+974'),
            new self(181, '(' . 'Reunion' . ')' . '+262'),
            new self(182, '(' . 'Romania' . ')' . '+40'),
            new self(183, '(' . 'Russia' . ')' . '+7'),
            new self(184, '(' . 'Rwanda' . ')' . '+250'),
            new self(185, '(' . 'Samoa' . ')' . '+685'),
            new self(186, '(' . 'San Marino' . ')' . '+378'),
            new self(187, '(' . 'Saudi Arabia' . ')' . '+966'),
            new self(188, '(' . 'Senegal' . ')' . '+221'),
            new self(189, '(' . 'Serbia' . ')' . '+381'),
            new self(190, '(' . 'Seychelles' . ')' . '+248'),
            new self(191, '(' . 'Sierra Leone' . ')' . '+232'),
            new self(192, '(' . 'Singapore' . ')' . '+65'),
            new self(193, '(' . 'Slovakia' . ')' . '+421'),
            new self(194, '(' . 'Slovenia' . ')' . '+386'),
            new self(195, '(' . 'Solomon Islands' . ')' . '+677'),
            new self(196, '(' . 'South Africa' . ')' . '+27'),
            new self(197, '(' . 'South Georgia and the South Sandwich Islands' . ')' . '+500'),
            new self(198, '(' . 'South Korea' . ')' . '+82'),
            new self(199, '(' . 'Spain' . ')' . '+34'),
            new self(200, '(' . 'Sri Lanka' . ')' . '+94'),
            new self(201, '(' . 'Sudan' . ')' . '+249'),
            new self(202, '(' . 'Suriname' . ')' . '+597'),
            new self(203, '(' . 'Swaziland' . ')' . '+268'),
            new self(204, '(' . 'Sweden' . ')' . '+46'),
            new self(205, '(' . 'Switzerland' . ')' . '+41'),
            new self(206, '(' . 'Syria' . ')' . '+963'),
            new self(207, '(' . 'Taiwan' . ')' . '+886'),
            new self(208, '(' . 'Tajikistan' . ')' . '+992'),
            new self(209, '(' . 'Tanzania' . ')' . '+255'),
            new self(210, '(' . 'Thailand' . ')' . '+66'),
            new self(211, '(' . 'Timor Leste' . ')' . '+670'),
            new self(212, '(' . 'Togo' . ')' . '+228'),
            new self(213, '(' . 'Tokelau' . ')' . '+690'),
            new self(214, '(' . 'Tonga' . ')' . '+676'),
            new self(215, '(' . 'Trinidad and Tobag' . ')' . '+1 868'),
            new self(216, '(' . 'Tunisia' . ')' . '+216'),
            new self(217, '(' . 'Turkey' . ')' . '+90'),
            new self(218, '(' . 'Turkmenistan' . ')' . '+993'),
            new self(219, '(' . 'Turks and Caicos Islands' . ')' . '+1 649'),
            new self(220, '(' . 'Tuvalu' . ')' . '+688'),
            new self(221, '(' . 'U.S. Virgin Islands' . ')' . '+1 340'),
            new self(222, '(' . 'Uganda' . ')' . '+256'),
            new self(223, '(' . 'Ukraine' . ')' . '+380'),
            new self(224, '(' . 'United Arab Emirates' . ')' . '+971'),
            new self(225, '(' . 'United Kingdom' . ')' . '+44'),
            new self(226, '(' . 'United States' . ')' . '+1'),
            new self(227, '(' . 'Uruguay' . ')' . '+598'),
            new self(228, '(' . 'Uzbekistan' . ')' . '+998'),
            new self(229, '(' . 'Vanuatu' . ')' . '+678'),
            new self(230, '(' . 'Venezuela' . ')' . '+58'),
            new self(231, '(' . 'Vietnam' . ')' . '+84'),
            new self(232, '(' . 'Wake Island' . ')' . '+1 808'),
            new self(233, '(' . 'Wallis and Futuna' . ')' . '+681'),
            new self(234, '(' . 'Yemen' . ')' . '+967'),
            new self(235, '(' . 'Zambia' . ')' . '+260'),
            new self(236, '(' . 'Zanzibar' . ')' . '+255'),
            new self(237, '(' . '"Zimbabwe"' . ')' . '+263'),
        ];
    }

}
